services:
  backend:
    build: .
    container_name: openrvdas-backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
      - ./db.sqlite3:/app/db.sqlite3
