"""removed configs.enabled

Revision ID: 0a51def167e4
Revises: 0f48d753432c
Create Date: 2026-01-18 13:24:57.175060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a51def167e4'
down_revision = '0f48d753432c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configs', 'enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('enabled', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
