"""removed config_text from cruise model

Revision ID: 0f48d753432c
Revises: 4b42896a6cb0
Create Date: 2026-01-15 14:39:34.217975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f48d753432c'
down_revision = '4b42896a6cb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cruise', 'config_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise', sa.Column('config_text', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
