"""Initial DB creation

Revision ID: 4938049611fc
Revises:
Create Date: 2025-09-27 08:28:41.086083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, String, Boolean, Integer, DateTime
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.asyncio import AsyncSession
from passlib.context import CryptContext
from datetime import datetime
from uuid import uuid4
from app.config import settings

# revision identifiers, used by Alembic.
revision = '4938049611fc'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('apikeys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('password_reset_tokens',
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('refresh_tokens',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('apikey_permissions',
    sa.Column('apikey_id', sa.String(length=36), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['apikey_id'], ['apikeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('apikey_id', 'route', 'method')
    )
    # ### end Alembic commands ###


    # --- Inserts for default roles and admin user ---
    conn = op.get_bind()

     # Tables for insert
    roles_table = table('roles', column('id', sa.UUID), column('name', String))
    users_table = table('users', column('id', sa.UUID), column('username', String))
    user_roles_table = table('user_roles', column('user_id', sa.UUID), column('role_id', sa.UUID))

    # Insert roles
    conn.execute(roles_table.insert().values(id=uuid4(), name='admin'))
    conn.execute(roles_table.insert().values(id=uuid4(), name='user'))

    # Hash admin password
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    hashed_password = pwd_context.hash(settings.default_admin_password)

    # Insert admin user
    conn.execute(
        sa.text(
            "INSERT INTO users (id, username, full_name, email, hashed_password, disabled) "
            "VALUES (:id, :username, :full_name, :email, :hashed_password, :disabled)"
        ).bindparams(
            id=uuid4(),
            username=settings.default_admin_username,
            full_name=settings.default_admin_fullname,
            email=settings.default_admin_email,
            hashed_password=hashed_password,
            disabled=False
        )
    )

    # Get admin role id
    result = conn.execute(roles_table.select().where(roles_table.c.name=='admin'))
    role_id = result.scalar_one()

    # Get admin user id
    result = conn.execute(users_table.select().where(users_table.c.username==settings.default_admin_username))
    admin_user_id = result.scalar_one()

    # Assign role
    conn.execute(user_roles_table.insert().values(user_id=admin_user_id, role_id=role_id))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apikey_permissions')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('apikeys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
