"""add expires_at to apikeys

Revision ID: 57dbf607eba2
Revises: 4938049611fc
Create Date: 2025-10-04 07:31:10.209228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57dbf607eba2'
down_revision = '4938049611fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikeys', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apikeys', 'expires_at')
    # ### end Alembic commands ###
