"""current_config --> active

Revision ID: 5c4eaa4f1d1e
Revises: 0a51def167e4
Create Date: 2026-02-17 10:06:42.156517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4eaa4f1d1e'
down_revision = '0a51def167e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('configs', 'current_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('current_config', sa.BOOLEAN(), nullable=False))
    op.drop_column('configs', 'active')
    # ### end Alembic commands ###
