"""added openrvdas-related tables

Revision ID: 9b78550ab220
Revises: 57dbf607eba2
Create Date: 2026-01-10 10:37:07.635676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b78550ab220'
down_revision = '57dbf607eba2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
